language: python
sudo: required
dist: xenial
python:
  - "3.7"
cache: pip
install:
  - pip install poetry
  - poetry install
script:
  - poetry run pytest --cov-report term-missing --cov-branch --cov=chitanda tests/
  - black -S -t py37 -l 79 --check chitanda tests
  - poetry run isort -rc -c chitanda tests
  - poetry run flake8 chitanda tests
after_success:
  - coveralls
