[tool.poetry]
name = "snowball"
version = "0.1.0"
description = "An IRC bot framework."
authors = ["dazzler <dazzler@riseup.net>"]
license = "BSD-2-Clause"
readme = "README.md"
repository = "https://github.com/dzlr/snowball"

[tool.poetry.scripts]
snowball = 'snowball.__main__:main'

[tool.poetry.dependencies]
python = "^3.6"
huey = "^1.10"
gevent = "^1.4"
pydle = "^0.9.1"

[tool.poetry.dev-dependencies]
poetry-setup = "^0.3.6"
isort = "^4.3"
flake8 = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
